### ISSUE TITLE
Fetching available surround modes

### ISSUE THREAD

**Issue by newt10** [JPHutchins/denonavr2016#1]
Do you know what is the command body in order to fetch all available surround sound modes?

Based on this and the XML returned by deviceInfo, I would guess it would be akin to 

<tx>
<cmd id="3">
<name>
GetSoundModeList
</name>
<list>
....
</list>
</cmd>
</tx>

Not sure what parameters to send to get the response

```
$ curl http://192.xx.xx.xx:8080/goform/AppCommand0300.xml -d 
'
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="3">
    <name>GetSoundModeList</name><list><param name="MOVIE"></param><param name="MUSIC"></param><param name="GAME"></param><param name="PURE"></param></list></cmd></tx>
'

# <---- I received the following response ----->
<?xml version="1.0" encoding="utf-8" ?>
<rx>
<cmd>
<name>GetSoundModeList</name>
<list>
</list>
</cmd>
</rx>
```

**Comment by JPHutchins** [comment]
See line 69 here https://www.github.com/JPHutchins/denonavr2016/tree/master/XML_data_dump.txt

Let me know if that does not work.

**Comment by JPHutchins** [comment]
Oh lmao I just realized you may be going down a rabbit hole - I wrote a parser to generate commands from deviceinfo.xml - do not waste your time, the schema is inconsistent and the whole process was irritating.  Notably, there is no obvious way to handle distinctions of endpoints.

**Comment by newt10** [comment]
> See line 69 here https://www.github.com/JPHutchins/denonavr2016/tree/master/XML_data_dump.txt
> 
> Let me know if that does not work.

The sound modes work but the sound mode list is basically a list of items within

**Comment by newt10** [comment]
Actually I was able to find it using some network sniffing

Here is the request XML

```
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="3">
    <name>GetSoundModeList</name>
    <list>
      <param name="genrelist"></param>
    </list>
  </cmd>
</tx>
```

and you get a response like this
```
<?xml version="1.0" encoding="utf-8" ?>
<rx>
<cmd>
<name>GetSoundModeList</name>
<list>
<param name="genrelist" control="2">2</param>
<list>
<value>
<listno>1</listno>
<dispname>Stereo</dispname>
<selected>0</selected>
</value>
<value>
<listno>2</listno>
<dispname>Dolby Audio - Dolby Surround</dispname>
<selected>0</selected>
</value>
<value>
<listno>3</listno>
<dispname>DTS Neural:X</dispname>
<selected>0</selected>
</value>
<value>
<listno>4</listno>
<dispname>DTS Virtual:X</dispname>
<selected>0</selected>
</value>
<value>
<listno>5</listno>
<dispname>Multi Ch Stereo</dispname>
<selected>1</selected>
</value>
<value>
<listno>6</listno>
<dispname>Rock Arena</dispname>
<selected>0</selected>
</value>
<value>
<listno>7</listno>
<dispname>Jazz Club</dispname>
<selected>0</selected>
</value>
<value>
<listno>8</listno>
<dispname>Matrix</dispname>
<selected>0</selected>
</value>
<value>
<listno>9</listno>
<dispname>Virtual</dispname>
<selected>0</selected>
</value>
</list>
</list>
</cmd>
</rx>
```

**Comment by newt10** [comment]
I think the above commands can be incorporated into the spec file to fetch various surround modes available.

**Comment by JPHutchins** [comment]
Ooooooh, super cool, nice work!  Check out my new push-based controller for
AV Receivers if you have a chance.
https://github.com/JPHutchins/pyavreceiver
I have also experimented with UPnP though the pub/sub is not comprehensive
- for example, it doesn't support power state!  yikes

**Comment by newt10** [comment]
That is cool! I was primarily trying to build some home automation that would automatically read the now playing info from apple tv and set-up corresponding sound mode on the AVR. The apple side to this is turning out to be a bit painful though!

**Comment by JPHutchins** [comment]
Of course it's painful.  It's all painful.  It's all undocumented and
archaic.  FWIW, as a sound guy, people should really just use "auto" or
"direct" on their receivers.  Every step of the signal chain from
distributor, to Apple TV, to TV, to receiver has logic for choosing the
"right sound mode".  Options like multi channel stereo are potentially
useful for multi room or something.  My new library won't give people the
option to choose DTS when the source is Dolby for example...  I have
opinions lol :wink:
